### ISSUE TITLE
auto_now_add overrides factoryboy params

### ISSUE THREAD

**Issue by boxed** [FactoryBoy/factory_boy#102]
Say I have a model:

``` python
class Foo(models.Model):
    foo = models.DateField(auto_now_add=True)
```

with a trivial factory FooFactory, if I then do:

``` python
print FooFactory(foo=date(2001, 1, 1)).foo
```

it prints the current date, not the one I specified. To me this is a violation of principle of least surprise.

**Comment by lmannering** [comment]
Quick question - how should this be implemented for auto_add (rather than auto_add_now)? I have an "updated" field, but whether I use models.DateTimeField(auto_now=True) or override the django model .save() method, I can't seem to get FactoryBoy to return the correct value of updated (LazyAttribute(lambda o: o.created + timedelta(hours=1)) or using the _create() method) - it always returns timezone.now(). 

What's the best way to go here?

**Comment by rbarrois** [comment]
@lmannering I'm not sure about the issue you're having?

Basically:
- If you set ``auto_now`` on a Django field, the current value of the field *will* be overwritten when calling ``.save()``
- Since that operation happens during the ``.save()`` step, its result cannot be seen in the factory (which operates *before* any instance of the model exists).

In other words, the way thinks work are:
1. factory_boy resolves all declarations into a set of values;
2. Those values are passed to ``MyModel.objects.create()``
3. During the actual ``.save()`` from Django's core, the value of ``updated`` is replaced with ``timezone.now()``

**Comment by boxed** [comment]
@lmannering maybe the solution is to use freezegun and circumvent this and other problems all together?

**Comment by pymen** [comment]
Here is my way to do it in a universal way with freeze gun https://stackoverflow.com/a/70364787/1731460

**Comment by ashirazi2** [comment]
> That's a built-in "feature" of Django: when a field has `auto_now_add=True`, Django will override any provided value with `django.utils.timezone.now()` ; this happens ''after'' factory_boy's code runs.
> 
> You have two options:
> 
> 1. Override your factory' `_create` function:
>  1. Replace `auto_now_add=True` with the `default` keyword argument to models:

I know this is an old thread, but there is a third method that I use; override the date without saving…
```python
class Foo(models.Model):
    created_at = models.DateField(auto_now_add=True)

foo = FooFactory.create()
foo.created_at = date(2001, 1, 1))
# use foo in assertion
```

**Comment by krystofbe** [comment]
> > That's a built-in "feature" of Django: when a field has `auto_now_add=True`, Django will override any provided value with `django.utils.timezone.now()` ; this happens ''after'' factory_boy's code runs.
> > You have two options:
> > 
> > 1. Override your factory' `_create` function:
> > 2. Replace `auto_now_add=True` with the `default` keyword argument to models:
> 
> I know this is an old thread, but there is a third method that I use; override the date without saving…
> 
> ```python
> class Foo(models.Model):
>     created_at = models.DateField(auto_now_add=True)
> 
> foo = FooFactory.create()
> foo.created_at = date(2001, 1, 1))
> # use foo in assertion
> ```

This was quite helpful. In addition to your approach, I found it necessary to include the .save() method to ensure the changes were persisted.
