### ISSUE TITLE
FuzzDate.start_date and end_date returns integer not date object.

### ISSUE THREAD

**Issue by tkreis** [FactoryBoy/factory_boy#299]
It seems like the documentation is out of date.

The comments show a date object being returned, but the code actually returns an integer (proleptic Gregorian ordinal).

the documentation:
http://factoryboy.readthedocs.io/en/latest/fuzzy.html#factory.fuzzy.FuzzyDate

here's the piece of code which seems to cause the difference:

```
self.start_date = start_date.toordinal()
self.end_date = end_date.toordinal()
```

https://github.com/rbarrois/factory_boy/blob/master/factory/fuzzy.py#L201

**Comment by jeffwidman** [comment]
We are trying to move away from generating fuzzy/fake values directly in FactoryBoy in favor of using https://github.com/joke2k/faker instead, see #271.

So while this issue is probably a bug, the long-term fix is likely going to be simply removing that code/docs. That said, if you want to submit a patch correcting the docs until we actually get around to removing that code, I'd be more than happy to accept it.

**Comment by rbarrois** [comment]
The doc is a pseudo-code example of what goes behind the scene; the ``start_date`` / ``end_date`` fields are actually implementation details, not public APIs.

I think I'll close this issue ;)
