### ISSUE TITLE
Factory with a self-referential foreign key is not saving to the database.

### ISSUE THREAD

**Issue by Sidon** [FactoryBoy/factory_boy#394]
I'm trying to create a fixture (Django 1.11) based on a model with a self-referential foreign key.
Ok, there is no error, Channel is saved, but Categories not.

My model.py:

```python
    class Channel(models.Model):
        name = models.CharField(max_length=100)
        def __str__(self):
            return self.name
    
    class Category(models.Model):
        name = models.CharField(max_length=100)
        channel = models.ForeignKey(Channel)
        parent = models.ForeignKey('Category', null=True)
        def __str__(self):
            return self.name
```

My facctories.py

```python  
    class ChannelFactory(factory.django.DjangoModelFactory):
        class Meta:
            model = Channel
 
     class CategoryFactory(factory.django.DjangoModelFactory):
        class Meta:
            model = Category
    
        channel_id=1
        parent = factory.SubFactory('core.factories.CategoryFactory')
```

My tests.py
```python
    tree = (('Books', None), ('National Literature', 'Books'), ('Science fiction', 'National Literature'))
    
    class ModelTestCase(TestCase):
        channel = ChannelFactory(
            name='Shoptest'
        )
    
        def test_models1(self):
            for node in tree:
                parent_name = node[1]
                parent = Category.objects.filter(name=parent_name)[0] if parent_name else None
                categ = CategoryFactory(
                    name=node[0],
                    channel=self.channel,
                    parent=parent,
                    parent__parent__parent=None
                )
```

**Comment by rbarrois** [comment]
Hi,

What do you mean by ``Categories`` is not saved?
Do you get an error message, or no items in the database? How do you check for its existence?

A specific thing to know about Django's TestCase is that each test function runs in a transaction (see [the docs](https://docs.djangoproject.com/en/1.11/topics/testing/overview/#writing-tests)).
This means that, with your example:
1. The test database is created
2. ``channel`` is created in the database when loading the test code
3. A transaction begin before ``test_models``
4. The categories are created within that transaction
5. The transaction is rolled back, leaving only ``channel`` in the database.

Another notes:
- since you set ``channel_id = 1`` in your ``CategoryFactory``, this might conflict with passing ``channel=``: both would work about the foreign key; the outcome will depend upon Django's behavior here.
- Passing ``parent__parent__parent=None`` isn't needed when you provide an explicit value for ``parent``, unless that value is itself a factory-related declaration.

**Comment by Sidon** [comment]
Yes you are right, I even forgot that the test database is temporary.
