### ISSUE TITLE
Unexpected keyword argument TypeError for classically mapped SQLAlchemy models

### ISSUE THREAD

**Issue by rhlk123** [FactoryBoy/factory_boy#410]
Here's a simple model class:

```
class Group(object):
    def __init__(self, groupname):
        self.group_id = None
        self.group_name = groupname
```
Table definition:
```
group_table = Table('GROUP_MASTER', bioram_metadata,
                    Column('group_id', Integer, primary_key=True),
                    Column('group_name', String(15), unique=True, nullable=False),
                    )
```
Mapping:
```
mapper(Group, group_table)
```

I'm trying to use factory_boy for functional testing using python unittest module

```
class GroupFactory(factory.alchemy.SQLAlchemyModelFactory):
    class Meta:
        model = Group

    group_name = 'ABC'
```

And create a group like so during the unittest module setUp():
```
grp = GroupFactory.create()
```

When I run the test, I get the following error :
```
======================================================================
ERROR: testGroup (sources.tests.testModels.TestModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\workbench\project\sources\tests\testModels.py", line 37, in setUp
    grp = GroupFactory.create()
  File "c:\workbench\project\venv\lib\site-packages\factory\base.py", line 568, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "c:\workbench\project\venv\lib\site-packages\factory\base.py", line 505, in _generate
    return step.build()
  File "c:\workbench\project\venv\lib\site-packages\factory\builder.py", line 279, in build
    kwargs=kwargs,
  File "c:\workbench\project\venv\lib\site-packages\factory\base.py", line 314, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "c:\workbench\project\venv\lib\site-packages\factory\alchemy.py", line 75, in _create
    obj = model_class(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'group_name'

----------------------------------------------------------------------
```

I've seen only declarative mapping examples for factory_boy. What should be changed to make it work for classically mapping ?

**Comment by rbarrois** [comment]
I'm not a SQLAlchemy expert — @jeffwidman might help more on this.

But I can easily explain the error: ``factory_boy`` doesn't parse much class metadata, it will pass all provided parameters to the target class' ``__init__``.

Since that function only accepts a ``groupname`` parameter, it crashes when provided with ``group_name=x``.

A simple solution might be to rename the field either in your ``Group.__init__`` function or in your factory.

**Comment by jeffwidman** [comment]
Is there a reason you need the classically mapped style? 

@rbarrois explained the problem well. Since classically mapped is a late binding of the table description to the class, not sure of an easy way to workaround this because FactoryBoy is passing directly to the class init. There may be a way, I'm just not sure as I've never seen a reason for using classical instead of declarative.

**Comment by drcongo** [comment]
I'm also getting this while porting a couple of projects to Python 3 from Python 2. I'm also using Flask-SQLAlchemy on both projects, so the mappings are done conforming to that - which according to their docs is the declarative way[1]. Oddly, the test suites ran fine under Python 2.7.13 but I get this issue on Python 3.5.3.

[1] http://flask-sqlalchemy.pocoo.org/2.1/models/
