### ISSUE TITLE
SubFactories still save with build method (Sqlalchemy)

### ISSUE THREAD

**Issue by 3lpsy** [FactoryBoy/factory_boy#417]
When calling build on a SQLAlchemyModelFactory, the SubFactories are still saved to the database.

```
class SqlFactory(factory.alchemy.SQLAlchemyModelFactory):
    class Meta:
        sqlalchemy_session = db.session
        sqlalchemy_session_persistence = 'commit'
```
```
BookFactory(SqlFactory):
    class Meta:
         model = Book
    name = Faker('word')
    author = SubFactory(AuthorFactory)
```
```
data = {'name': 'hello darkness'}
book = BookFactory.build(**data)
```

book is now an unsaved sqlalchemy instance as expected, but a author entry has been added to the database and is now a sqlalchemy instance that has been saved.

I would expect build() not to save/persist sub properties. If this is indeed intended behavior, any advice on how to modify the code so that author is not saved but instantiated would be great.

Thanks

**Comment by jeffwidman** [comment]
My memory is a bit hazy, and I don't have time to research the details, but from what I recall your problem is here: `sqlalchemy_session_persistence = 'commit'`

As soon as the Author is created, it's immediately committed. Instead, I would set that to `None` or `'flush'`, depending on what you're trying to achieve. A flush will hit the DB, but inside of the transaction, so you can roll it back at the end of your test / dev work if you want. `None` might also help with your desired behavior, it really depends on whether you're trying to altogether avoid a DB hit or just keep it nested within a transaction.
