### ISSUE TITLE
Link to external projects as examples of how to use FactoryBoy?

### ISSUE THREAD

**Issue by dfee** [FactoryBoy/factory_boy#419]
A few times now I've tried to figure out how to create One-to-One mappings with FactoryBoy, and I typically have to re-learn how to do it. Well, this time I was smarter, and decided to reference old code. However, due to the changes in `2.9.x`, I've had to come up with a new solution.

I present: https://github.com/dfee/factoryboy_oto_demo

As the README suggests, this demonstrates how to build simple and complex one-to-one mappings with FactoryBoy.

An example of a simple mapping might be a User and Profile that reference each other.
An example of a complex mapping might be a User who has an Image as `user.profile_picture` and another image as `user.header_picture` (technically, it would meet the criteria of both a One-to-One and a One-to-Many).

The solution involves using `factory.post_generation` on each Factory side.

Alas, I'm publishing this here as an issue, so that it's a) seen by others who come this way, and b) as a way to inform FactoryBoy core devs that maybe this should be documented somewhere.

Cheers,

**Comment by jeffwidman** [comment]
At first glance, this looks great!

I'm not sure how to incorporate this into the docs though... it's too much code to embed inline, and I'm leery of directly linking to external code we don't control because we can't guarantee it stays updated with the latest releases. 

Perhaps we could have a section titled "Example projects using Factory Boy" and add a warning that it's external code not guaranteed to have the currently recommended way to do things? There are a few others we could potentially link to as well, for example I know the PyPA uses [FactoryBoy for testing the new Warehouse project](https://github.com/pypa/warehouse/search?utf8=%E2%9C%93&q=factory&type=).

I know I personally would have appreciated something like that when I started with FactoryBoy... @rbarrois what do you think?

**Comment by dfee** [comment]
I agree with you 100%. I have no interest in maintaining that example repo for each new release (though I will commit to leaving it up). [ugh, I probably should pin the install_requires 'factoryboy==2.9.2'. and call that out in the README.]

The reason I threw the repo together in the first place was because there was too much code to paste into an issue. As long as users are savvy enough to explore the issues, hopefully they'll see this, nonetheless!
