### ISSUE TITLE
Question: Parallel

### ISSUE THREAD

**Issue by listingmirror** [FactoryBoy/factory_boy#460]
factory_boy works amazing single.. but I am having an issue in parallel mode..

If I launch my tests with something like

`python manage.py test -k --parallel=4`

Some of my models have a field setup like this:

`sku = factory.Sequence(lambda n: 'sku-%d' % n)`

I notice that 1 in 20 runs or so, two of my sequences collide -  Which makes sense, nothing from one fork to know that another fork has already uses a sequence, so both decide to make a SKU-99 at the same time.

What is a normal strategy to prevent this? Should I start each sequence at process_pid * 1000 or something?

**Comment by rbarrois** [comment]
Hi,

This looks like a good solution, but would break if you create too many objects.
Alternatives would be:
- Override the subsystem computing the next sequence to lock the table and use ``max(pk) + 1``
- Add a feature to factory_boy which would handle a global "sequence offset", so that the sequence is computed as ``counter * proc_count + proc_rank`` — but we'd have to be able to know what our current rank is.

**Comment by listingmirror** [comment]
@rbarrois max(pk) seems like a race condition though?  

I am not sure how to get proc_rank inside python, hum

**Comment by rbarrois** [comment]
That's why I suggested locking the table ;)

I don't think any specific changes are needed for your issue, so I'll close it if that's fine by you?

Feel free to reopen it if needed ;)

**Comment by listingmirror** [comment]
@rbarrois sure!  I added some code to key off of the PID and it's doing better so far
