### ISSUE TITLE
RelatedFactory seems not to set a built object

### ISSUE THREAD

**Issue by l3msh0** [FactoryBoy/factory_boy#490]
Here are models and factories which I implemented referring to the [document](http://factoryboy.readthedocs.io/en/latest/reference.html#relatedfactory) of `RelatedFactory`.

models.py

```python
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=100)
    capital_of = models.ForeignKey('factory_test.Country', on_delete=models.CASCADE)


class Country(models.Model):
    lang = models.CharField(max_length=100)
    capital_city = models.ForeignKey('factory_test.City', on_delete=models.CASCADE, null=True)
```

factories.py
```python
from factory.django import DjangoModelFactory

from . import models


class CityFactory(DjangoModelFactory):
    class Meta:
        model = models.City

    capital_of = None
    name = "Tronto"


class CountryFactory(DjangoModelFactory):
    class Meta:
        model = models.Country

    lang = 'fr'
    capital_city = factory.RelatedFactory(CityFactory, 'capital_of', name='Paris')

```

I expect that a `City` object is set to `county.capital_city` if I execute `country = CountryFactory()` but actual value is `None` instead.

Is this intended behaviour? I'm not sure but I wonder an object built by RelatedFactory should be set to parent instance like [this](https://github.com/l3msh0/factory_boy/commit/3aa4ebe6e025434fab27a4aabf3698964e2a3812).

**Comment by rbarrois** [comment]
It is expected behavior: the ``factory.RelatedFactory`` will create an object from the given factory and the newly created instance.

By the way, your model has an issue: you have no guarantee that ``country.capital_city.country == country``.
I'd change your model to:

```python
class City(models.Model):
    name = models.CharField(max_length=200)
    capital_of = models.OneToOneField(
        Country,
        related_name='capital_city',
        blank=True, null=True, on_delete=models.CASCADE,
    )

class Country(models.Model):
    name = models.CharField(max_length=200)
    # Django will provide each Country instance with a magical `capital_city` attribute
```

With those models, the ``CountryFactory`` would create a ``City`` pointing (through its one-to-one field) to the ``Country`` instance; Django's related field feature would then allow you to query ``country.capital_city`` and fetch that city.
