### ISSUE TITLE
Recipe: ImageField(from_file=FuzzyChoice()) ?   (django)

### ISSUE THREAD

**Issue by gotexis** [FactoryBoy/factory_boy#576]
Hey

Sorry I'm back for more recipes...

Let's say I have 1,000 existing images in `D:\demo_images\`

I want to use them to create random image objects in database.

So, I am doing this:

```python

images = os.path.join( "d:/demo_images/", os.listdir('d:/demo_images/'))

class ImageFactory(factory.DjangoModelFactory):
    class Meta:
        model = Image
    shop                           = SubFactory('test.factory_codex.ShopFactory')
    image                          = factory.django.ImageField(from_file=FuzzyChoice(images))
```

Is it gonna work?

update:

Can confirm this works, but need to change `from_file` to `from_path`.

Further, this will copy the image from `d:/demo_images` to `MEDIA_ROOT`

Is there any way to disable this behaviour?

**Comment by rbarrois** [comment]
It will indeed work, as you've seen ;)

However, copying the images to ``MEDIA_ROOT`` is mandatory: this is the way Django works, any media file needs to exist within `MEDIA_ROOT` (where your webserver will serve it).

You might be able to hack something with hard links under Linux, I'm not so sure about Windows.
Note however that this is outside the scope of `factory_boy`: I'd try to reach your goal with code manipulating simple, native Django Model instances; once that works, convert it to factories or fields or extension points.

NB: Since this is more a question than an issue, and outside the core factory features, I'm closing it; feel free to reopen it if you disagree :-)
