### ISSUE TITLE
Documentation make it look like I've got to inherit factories from factory.Factory

### ISSUE THREAD

**Issue by x-yuri** [FactoryBoy/factory_boy#587]
#### The problem
I've spent quite a while trying to figure out why my factory doesn't return saved Django model instance as promised. All the examples [here][1] inherit factories from `factory.Factory`. From what I can see `factory.Factory` doesn't try anything as near as to [saving][2] the model. It looks as if `factory.Factory` is an abstract class (not to be used directly).

[1]: https://factoryboy.readthedocs.io/en/2.11.1/
[2]: https://github.com/FactoryBoy/factory_boy/blob/v2.9.0/factory/base.py#L546

#### Proposed solution
Improve the documentation. Depends on what `factory.Factory` is for. For example, choose the popular ORM to use for examples. Or state clearly before inheriting from `factory.Factory` that it's not to be used with ORMs. And probably explain what `factory.Factory` is for.

**Comment by federicobond** [comment]
Hi @x-yuri, thanks for reaching out. ORM support is described [here](https://factoryboy.readthedocs.io/en/2.11.1/#orm-support). `factory.Factory` is meant for generating plain Python objects.

I sense that you are frustrated because you lost quite a bit of time figuring this out, but without a concrete proposal in the form of a pull request there isn't much we can do. Feel free to propose changes to the docs that address this issue.
