### ISSUE TITLE
need revise docs Many-to-many for SQLAlchemy

### ISSUE THREAD

**Issue by kobayashi** [FactoryBoy/factory_boy#688]
#### The problem
Many-to-Many documentation is not work for SQLAlchemy. 
This is described in #121 
#### Proposed solution
[Simple Many-to-many relationship](https://factoryboy.readthedocs.io/en/latest/recipes.html#simple-many-to-many-relationship) in the docs should not use add but append.

#### Extra notes
None

**Comment by rbarrois** [comment]
Hi!

Indeed, the example is geared at Django (the community from which factory_boy originates); but since we support more ORMs, it would be better to have clearer examples for each.

I can see a couple of options for this:
1. Splitting the `recipes` section: for pure Python, for Django, for SQLAlchemy;
2. Splitting the examples in each recipe, with examples for Django, SQLAlchemy, etc.

I feel that option 1 would be easier to use: it would allow us to use the specific terms used within each framework; however, it would require slightly more work to write and maintain.

Since I'm not too familiar with SQLAlchemy, it would be really helpful for me if you could point out the various points of the `recipes` section which don't translate properly to SQLAlchemy.
For instance, if you open a pull request where you simply highlight or comment all those items, I'll be able to use those to rewrite and split the docs for clearer examples ;)

**Comment by rbarrois** [comment]
Oops, I just saw that you had provided a pull-request to fix it; I'll merge it to get started, but the idea of splitting the `recipes` section between pure Python, Django and SQLAlchemy still holds — I'd love to get your help here !

**Comment by kobayashi** [comment]
Thanks to care this @rbarrois . Sure, I will make another PR to split the `recipes` section!
