### ISSUE TITLE
'Iterator' object is not callable

### ISSUE THREAD

**Issue by mazlum** [FactoryBoy/factory_boy#736]
##### Model / Factory code
```python
class TestFactory(DjangoModelFactory):
    build = Iterator(EXAMPLE_LIST)
```

##### The issue
*Model field name is "build". And if i try TestFactory.build(), factory_boy says ''Iterator' object is not callable' *

**Comment by rbarrois** [comment]
`build` is a reserved name — it provides the `TestFactory.build()` method.

In order to provide the right field name to the model without conflicting with FactoryBoy, you must use [`Meta.rename`](https://factoryboy.readthedocs.io/en/latest/reference.html#factory.FactoryOptions.rename):

```python
class TestFactory(factory.django.DjangoModelFactory):
    build_ = factory.Iterator(EXAMPLE_LIST)

    class Meta:
        rename = {'build_': 'build'}
        model = Test
```

By the way, this looks more like a "how do I?" question than a bug report or a feature request, and might be better suited for StackOverflow :wink:
