### ISSUE TITLE
Release minor version to address solved bugs

### ISSUE THREAD

**Issue by bcfurtado** [FactoryBoy/factory_boy#745]
#### The problem
Hello, recently came across this issue https://github.com/FactoryBoy/factory_boy/issues/424 in a project that I'm working on and I noticed that was fixed last year by this PR https://github.com/FactoryBoy/factory_boy/pull/592 , but since then we haven't released yet.

#### Proposed solution
I see that we are in the middle of a major release that will address this and other recent fixed issues, but given [that we do not have a timeline](https://github.com/FactoryBoy/factory_boy/milestone/5) for the that, I would like to suggest a minor release that would release this bug fix (and potentially others).

Thanks for the great work! 💪

**Comment by francoisfreitag** [comment]
Thank you for the report.
I privately emailed Raphaël (who’s in charge of releases) about making a release last week, to drop Python 2 support.
The milestone on GitHub has not been updated to reflect that goal. What is shown for a 3.0 should actually be moved to a 4.0.

With a major release planned soon, I don’t think a minor release is needed?

From Raphaël, here’s the work that’s holding up the next release:
- [ ] Fix readthedocs builds (#744)
- [ ] Review the changelog versus actual commits to make sure all changes are logged
- [ ] Check documentation for consistency with changes

I’ll try to address the remaining issues this week, so that we’re in a good position for the release.

**Comment by francoisfreitag** [comment]
I just updated the milestones to clear up 3.0.

**Comment by bcfurtado** [comment]
Hi @francoisfreitag ,

It was nothing. Thanks for getting back to me quickly. 

If we are planning a release soon, I agree that we can skip the minor release so we can primarily focus on the new version release.

**Comment by rbarrois** [comment]
@francoisfreitag having taken a look at the current ChangeLog, I think we should also add a "Migration / breaking changes" section — for instance, removing the `factory.django` shortcut will break lots of code.

**Comment by francoisfreitag** [comment]
Good idea! I opened https://github.com/FactoryBoy/factory_boy/pull/753/ with mappings from the broken import to recommended import.
