### ISSUE TITLE
Post-generated attribute of RelatedFactoryList isn't generated

### ISSUE THREAD

**Issue by kabdallah-galileo** [FactoryBoy/factory_boy#831]
#### Description
In order to automatically chain Factories whose underlying models aren't explicitly related all the way down the chain, I use a `post_generation` hook on a child `SubFactory` that's implicitly related through my code's business logic. When generating a child alone, the `post_generation` hook succeeds. However, when trying to generate a child via an explicitly related parent, the `post_generated` attributes aren't generated.

#### To Reproduce
Example: while the Shoe object can exist independently of a Child, in practice a child will always have a left and right shoe. However, without explicit relations such as FK, the relation can't be mocked using RelatedFactory or SubFactory. 

```python
from factory import Factory, RelatedFactoryList, Faker, post_generation
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, Unicode, create_engine, ForeignKey
from factory.alchemy import SQLAlchemyModelFactory
from sqlalchemy.orm import scoped_session, sessionmaker, relationship

Base = declarative_base()
engine = create_engine('sqlite://')
session = scoped_session(sessionmaker(bind=engine))


class Parent(Base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)

    children = relationship("Child", back_populates="parent")


class Child(Base):
    __tablename__ = 'child'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('parent.id'))
    name = Column(Unicode())

    parent = relationship("Parent", back_populates="children")


class Shoe(Base):
    __tablename__ = 'toy'
    id = Column(Integer, primary_key=True)
    foot = Column(Unicode())


class ShoeFactory(SQLAlchemyModelFactory):
    class Meta:
        model = Shoe
        sqlalchemy_session = session
    foot = Faker('random_element', elements=["right", "left"])


class ChildFactory(SQLAlchemyModelFactory):
    # Child has to have at least 1 right shoe and one left shoe.
    class Meta:
        model = Child
        sqlalchemy_session = session
    name = Faker('word')

    @post_generation
    def post_generated_attribute(self, create, extracted, **kwargs):

        self.right_shoe = ShoeFactory(
            foot="right"
        )

        self.left_shoe = ShoeFactory(
            foot="left"
        )


class ParentFactory(SQLAlchemyModelFactory):
    class Meta:
        model = Parent
        sqlalchemy_session = session
    children = RelatedFactoryList(ChildFactory, 'parent', size=1,)
```
##### The issue
When generating an ChildFactory alone, the `post-generation` hook succeeds. However if generating a Parent, somehow the SubFactory `child` attribute doesn't generate the `shoes` post-attribute.

```python
# Generating child with no parents.
orphan = ChildFactory()

try:
    orphan_right_shoe = orphan.right_shoe
except:
    print("Orphan has no right shoe")
else:
    print("Orphan's right shoe is on")

try:
    orphan_left_shoe = orphan.left_shoe  # shoes are there
except:
    print("Orphan has no left shoe")
else:
    print("Orphan's left shoe is on")

# Generating child through parents
parent = ParentFactory()
child = parent.children

try:
    child_right_shoe = parent.children.right_shoe
except:
    print("Child has no right shoe")
else:
    print("Child's right shoe is on")

try:
    child_left_shoe = parent.childern.left_shoe
except:
    print("Child has no left shoe")
else:
    print("Child's left shoe is on")

>>>
Orphan's right shoe is on

Orphan's left shoe is on

Child has no right shoe

Child has no left shoe
```
The error on the Child reads:
```shell
Traceback (most recent call last):
  File "scratch.py", line 58, in <module>
    child_toy = parent.children.toy
AttributeError: 'InstrumentedList' object has no attribute 'toy'
```

#### Notes
This also seems to happen on `RelatedFactory` (which would make sense since the `List` is an extension).
Any ideas why this would be happening? Otherwise, any recommendations on how to do the desired above (i.e. generate a parent, with children, with shoes)? Thanks!

**Comment by rbarrois** [comment]
The issue stems from the ORM's instance management.

When you reach `parent.children`, what you get is likely not the in-memory instance of `child` that was generated through the call, but another object fetched by SQLAlchemy's hidden session store.

The `RelatedFactory` and `RelatedFactoryList` mechanisms don't provide a mean to retrieve the object they generate — they are basically side-effect generators.
The known methods to fetch those side-effect objects are:
1. If their creation code attaches them to the related (calling) object — for instance in `Children.__init__(self, parent, ...)` having `parent.children.append(self)`;
2. If the instances are written to some internal store, from which they can be retrieved — typically saved to a database, and fetched through your `parent.children` attribute;
3. By manually adding a reference on the parent object, as you've done in your code.

Here, I believe you should simply add some reverse SQLAlchemy relationship from `Child` to `Shoe`, as you've done between `Parent` and `Child`.

### Under the hood

Technically, what happens when you call `ParentFactory` is:
1. Resolve `ParentFactory`'s declarations — none in your example
2. Generate the instance: `a_parent = Parent(); session.add(a_parent)`
3. Generate related instances — here `ChildrenFactory(parent=a_parent)`
4. Resolve `ChildrenFactory`'s declarations — provides, for instance, `name="John"`
5. Generate the instance: `a_child = Child(name="John", parent=a_parent); session.add(a_child)`
6. Generated related instances — here both `ShoeFactory()`
7. Generate the first shoe: `a_shoe = Shoe(); session.add(a_shoe); a_child.shoe_left = a_shoe`
8. Generate the second shoe: `another_shoe = Shoe(); session.add(another_shoe); a_child.shoe_right = another_shoe`
9. Return `a_parent`
10. `a_child` is no longer referenced by anything, and **is garbage collected**, as are `a_shoe` and `another_shoe`. Their data remains in SQLAlchemy's session or in your SQL database, though.

Since no attribute was set on `a_parent`, `a_parent.children` simply goes through SQLAlchemy default handlers, which would generate a fresh object from its session state. You receive a new `Child` subclass, with the proper ID and name, but none of the attributes that were set in your factories — they were discarded when it was garbage collected.

**Comment by kabdallah-galileo** [comment]
Apologies for the late reply, thanks for the detailed explanation and suggestions - the reverse SQLAlchemy relationship did the trick.

Merci!
