### ISSUE TITLE
Docs: 'Usage' says the default strategy is .create(), not .build()

### ISSUE THREAD

**Issue by Ben-Hampson** [FactoryBoy/factory_boy#859]
The [homepage of the docs](https://factoryboy.readthedocs.io/en/stable/index.html#using-factories) says:

> You can use the Factory class as a shortcut for the default build strategy:
> ```py
> # Same as UserFactory.create()
> user = UserFactory()
> ```

Maybe I'm misunderstanding something, but shouldn't it be: "Same as `UserFactory.build()`", not "Same as `UserFactory.create()`"?

**Comment by rbarrois** [comment]
That's indeed a bug, thanks for noticing it ;)

**Comment by rbarrois** [comment]
And fixed through #860, thanks a lot!

**Comment by yuekui** [comment]
Sorry guys, this fix really confused me: Isn't `create` the "default" strategy? When did we changed the default strategy from `create` to `build`? [FYI](https://github.com/FactoryBoy/factory_boy/blob/17e2b6703f1b8c8bbf3ad59ce06f83e2e3c9cbf5/factory/base.py#L97-L99)

**Comment by rbarrois** [comment]
@yuekui Thanks for the notification! I haven't checked, and was sure that the default strategy had been set to `.build()`; since `.build()` and `.create()` as strictly identical for standard factories, this was only a difference for ORM-related factory subclasses.

I'm fixing the docs the other way around right now!
