### ISSUE TITLE
"incorrect date value" is thrown with a specific date of 2021-03-28

### ISSUE THREAD

**Issue by karina-klinkeviciute** [FactoryBoy/factory_boy#907]
#### Description
I am trying to generate some data with Factory Boy. The models for which I am trying to generate it have DateTimeFields. I added a date_time_between from Faker to generate those and it works alright until it generates a date of `2021-03-28` with any time. Then it throws an error:

`django.db.utils.OperationalError: (1292, "Incorrect datetime value: '2021-03-28 03:11:39' for column 'x' at row 1")`
other examples:
 `django.db.utils.OperationalError: (1292, "Incorrect datetime value: '2021-03-28 03:47:18' for column 'y' at row 1")`

`"Incorrect datetime value: '2021-03-28 03:41:23' for column 'z' at row 1"`

as you can see, the date is always the same, but the time is different

I tried to save the same date manually with Django and it worked, but when I tried to save it manually with FactoryBoy, it didn't:

```python
class ClickFactory(ClickFactoryMixin, DjangoModelFactory):

    class Meta:
        model = Click

    lookup_widget_uid = LazyAttribute(fake_uuid)
```

With Django:
```python
x = X(ts='2021-03-28 03:11:39')
x
Out[18]: <X: X object ({"ts": "2021-03-28 03:11:39"})>
```

With FactoryBoy:

```python
x2 = XFactory.create(ts='2021-03-28 03:11:39')
```

and got error:

`MySQLdb._exceptions.OperationalError: (1292, "Incorrect datetime value: '2021-03-28 03:11:39' for column 'x_ts' at row 1")`

#### To Reproduce
*Share how the bug happened:*

##### Model / Factory code
```python

class X(models.Model):

    ts = models.DateTimeField()



def fake_ts(obj):
    faker.Faker.seed()
    return faker.Faker().date_time_between(start_date="-1y", end_date="now")

class XFactory(DjangoModelFactory):

    class Meta:
        model = X

    ts = LazyAttribute(fake_ts)


```

##### The issue
*Add a short description along with your code*

```python
# Include the code that provoked the bug, including as full a stack-trace as possible
```

#### Notes
*Add any notes you feel relevant here :)*

**Comment by rbarrois** [comment]
Your issue is that `Faker` generates a seemingly valid date, but it happens to fall during the transition to daylight saving time in your timezone, which is rejected by MySQL.

In your Django code, you'll have the issue when calling `x.save()`, which is the moment where the data will hit the database.

I recommend one of the following:
- Switching to timezone-aware datetimes (with `factory.fuzzy.FuzzyDateTime`);
- Telling your model that the provided datetime is an UTC datetime, not a naive datetime to be understood in the current process timezone;
- Or telling Faker to use a specific timezone (see the `tzinfo` parameter at https://faker.readthedocs.io/en/master/providers/faker.providers.date_time.html#faker.providers.date_time.Provider.date_time_between).

**Comment by karina-klinkeviciute** [comment]
Thanks!
