### ISSUE TITLE
DecimalField gives an error when floats are provided

### ISSUE THREAD

**Issue by shivan-s** [FactoryBoy/factory_boy#973]
#### Description
An error with DecimalField creation.

#### To Reproduce
When running tests using pytest.

##### Model / Factory code
```python
# models
class Lift(models.Model):
    ...

    bodyweight = models.DecimalField(
        blank=True, max_digits=5, decimal_places=2
    )

# factories
class LiftFactory(factory.DjagoModelFactory):
    ...
    
    @factory.lazy_attribute
    def bodyweight(self):
        return round(random.uniform(50, 150), 2)

```

##### The issue
When running `pytest`, the following error occurs.

```python
django.core.exceptions.ValidationError: {'bodyweight': ['Ensure that there are no more than 2 decimal places.']}
```

##### However

However, when I wrap the `random.uniform` with `Decimal`, it works!! Like so:
```python
return round(Decimal(random.uniform(50, 150), 2))
```

#### Notes
I am using:
- django 4.1.1
- factoryboy 3.2.1
- pytest 7.1.3
- pytest-django 4.5.2
- pytest-factoryboy 2.5.0

Also, I apologise, I don't know if this is an issue with `factoryboy` or `django`. I've also submitted a ticket to Django and will update on any changes.

Is this a problem with how float and decimal types are dealt with? Or am I doing something wrong?

I apologise, I don't know if this is a "mistake" with `factoryboy` or `django`.

**Comment by rbarrois** [comment]
If your field is a `DecimalField`, you should provide a `Decimal` instance.
When one passes a `float` to `decimal.Decimal`, Python will use the exact value of the float for the decimal, in order to avoid any loss of precision:

```python
>>> x = 0.3
>>> decimal.Decimal(x)
Decimal('0.299999999999999988897769753748434595763683319091796875')
```

In order to convert a float into a decimal, the recommanded option is to round the resulting value (see the [docs for the `decimal` module](https://docs.python.org/3/library/decimal.html) for details):
```python
>>> x = 0.3
>>> round(decimal.Decimal.from_float(x), 2)
Decimal("0.30")
```

In your specific case, I would recommend using either [`factory.fuzzy.FuzzyDecimal`](https://factoryboy.readthedocs.io/en/stable/fuzzy.html#fuzzydecimal) or [`factory.Faker("pydecimal")`](https://faker.readthedocs.io/en/master/providers/faker.providers.python.html#faker.providers.python.Provider.pydecimal):

```python
bodyweight = factory.fuzzy.FuzzyDecimal(low=50, high=150, precision=2)
```

Both `factory.fuzzy.Fuzzy*` and `factory.Faker(...)` declarations are hooked into factory_boy's randomness management system, which enables you to reproduce those values as described in https://factoryboy.readthedocs.io/en/stable/reference.html#randomness-management.

Hope that helps!

**Comment by shivan-s** [comment]
Thank you!
