### ISSUE TITLE
Add SQLAlchemy support for get_or_create()

### ISSUE THREAD

**Issue by fweep** [FactoryBoy/factory_boy#99]
I'm not sure this should be opened as an issue, but I can't figure out how to do it...

Is there any way to re-use existing records with factory_boy, if they already exist? I can't find anything in the documentation.

Here's my scenario:

I've got an `AddressFactory` for my `Address` model. Every `Address` has an associated `Country`. I'd like to have my `AddressFactory` create the `Country` if it doesn't exist, and re-use it if it does.

I know that I can create a `Country` manually, and pass it to the `AddressFactory` to be used. This works ok for a first-level nesting, but it gets complicated when there's e.g. a `User` who has an `Address` which has a `Country`. I'd like to avoid having to pass it all the way down the chain.

For most fields, I get around this problem by using sequences to ensure unique names, etc. In this case, I'd really like to re-use existing countries.

I've tried to come up with a way to do this dynamically using lazy attributes, but haven't had any luck so far.

Thanks!

**Comment by jeffwidman** [comment]
@rbarrois I'd like to tackle adding `get_or_create` behavior for SQLAlchemy. 

Can you provide a little guidance where in the code I should be looking? 

I was assuming that I just add a SQLAlchemy-specific `get` call, but then I noticed https://github.com/rbarrois/factory_boy/issues/239#issuecomment-154663287. Is the refactoring something you plan to do eventually? Should it preclude adding `get_or_create` for SQLAlchemy?

**Comment by rbarrois** [comment]
@jeffwidman the bigger refactor isn't likely to come right now (it would alter lots of internals to allow passing down the current "calling" context").

However, adding support for ``get_or_create()`` can be done without it, it would just have the same limitations as the Django version.

The interesting Django-side code lies in:
- https://github.com/rbarrois/factory_boy/blob/master/factory/django.py#L92 (defining the option)
- https://github.com/rbarrois/factory_boy/blob/master/factory/django.py#L148 (the actual code)
- https://github.com/rbarrois/factory_boy/blob/master/factory/django.py#L171 (the hook to get into ``_get_or_create()``)

**Comment by jeffwidman** [comment]
Thanks. Might take me a little while to get to this, but it's on my eventual todolist. 

Thinking aloud:
Part of me does wonder if it's better handled as a recipe in the docs illustrating how to code your own SQLAlchemy DB check... otherwise I'm afraid we might get issue from time to time from people not realizing the potential limitations. Plus I'm not positive the simplicity adds that much--in a reasonable percentage of the times where I've needed something like this, I've also needed to further customize the `get` check somehow, so a built-in wouldn't have worked in those situations.

**Comment by m1yag1** [comment]
Does someone have a recipe of getting something like this to work?

**Comment by jeffwidman** [comment]
If you want to stay at the ORM layer, just do a `one_or_none()` on your model, check the result and if it's none, then create something. `one_or_none()` will be faster than a `get()` since it only returns a single item if it exists, although the absolute fastest is actually dropping into SQLAlchemy core to run a SQL `EXISTS` query: http://stackoverflow.com/questions/7646173/sqlalchemy-exists-for-query

**Comment by darkanthey** [comment]
Another one SqlAlchemy avoid duplication implementation.

`    class StaticFactory(BaseFactory):
        __static_exclude = ('__static_exclude', '__static_cache',)
        __static_cache = {}
     
        @classmethod
        def _create(cls, model_class, *args, **kwargs):
            """Helper for avoid duplicate factory"""
     
            # Exclude static cache
            cls._meta.exclude += cls.__static_exclude
     
            _unique_key = None
     
            # Get first unique keys from table. I'll be cache key.
            for col in model_class.__table__.columns:
                if any([col.primary_key, col.unique]):
                    _unique_key = kwargs.get(col.name)
                    if _unique_key:
                        break
     
            _instance = cls.__static_cache.get(_unique_key)
            if _instance:
                return _instance
     
            _session = cls._meta.sqlalchemy_session
            with _session.no_autoflush:
                obj = model_class(*args, **kwargs)
                _session.add(obj)
                cls.__static_cache.update({_unique_key: obj})
                return obj
`

**Comment by rbarrois** [comment]
This has finally been added last year ;)
